### PR TITLE
update m5stickc project docs page

### PR DESCRIPTION
**Pull request by mbz4**

### CODE REVIEW

**Comment by ulno** [comment]
as teh display is turned, the correct fix would be actually bottom, below, or down - please change into one of these (also on screenshot and flow)

**Comment by mbz4** [comment]
hi, please help me understand in context
>  the correct fix would be actually bottom, below, or down

to which files did you refer to for administering the correct fix?

- m5stickc documentation
  - example codeblock?
  - node-red flow?
- m5stickc driver files? (not changed here)

**Comment by mbz4** [comment]
image
assuming context is the node-red flow w/ associated screenshot

preparing fix

**Comment by mbz4** [comment]
hey, committed the requested adjustments 
+ tested working demo

**Pull request merged**
